### ISSUE TITLE
archive this repo?

### ISSUE THREAD

**Issue by SethTisue** [eed3si9n/verify#212]
@eed3si9n it seems like activity here has more or less ceased. shall we archive the repo?

**Comment by eed3si9n** [comment]
I actually use Verify to test things. If it's ok, can I transfer it to my own as eed3si9n/verify?

**Comment by SethTisue** [comment]
yes, I think that would be best

**Comment by eed3si9n** [comment]
Transferred.

**Comment by SethTisue** [comment]
(You might need to notify the Steward of the change if you still want updates.)
